#! /usr/bin/python3

import schedule
import time
import os

def job():
    os.system('python3 report.py')

schedule.every().day.at('10:00').do(job)
schedule.every().day.at('15:00').do(job)
schedule.every().day.at('20:00').do(job)

while True:
    schedule.run_pending()
    time.sleep(30 * 60)
